name 'asdf'
maintainer 'Fernando Aleman'
maintainer_email 'fernandoaleman@mac.com'
license 'Apache-2.0'
description 'Installs and configures asdf'
version '2.0.0'
chef_version '>= 16'

supports 'debian'
supports 'ubuntu'
supports 'amazon'
supports 'centos'
supports 'redhat'
supports 'fedora'
supports 'scientific'
supports 'freebsd'
supports 'suse'
supports 'opensuse'
supports 'opensuseleap'

depends 'ark'
