name "asdf"
maintainer "Fernando Aleman"
maintainer_email "fernandoaleman@mac.com"
license "Apache-2.0"
description "Installs and configures asdf"
version "1.0.0"
chef_version ">= 15"

issues_url "https://github.com/asdf-chef/asdf/issues"
source_url "https://github.com/asdf-chef/asdf"

supports "debian"
supports "ubuntu"
supports "amazon"
supports "centos"
supports "redhat"
supports "fedora"
supports "scientific"
supports "freebsd"
supports "suse"
supports "opensuse"
supports "opensuseleap"

depends "ark"
